###########################################################
#   conda dependency installer
#
#  First time run use  $ conda env create -f conda.yml
#  Next run use $ conda env update -f conda.yml
#  To remove env: conda remove -n grabaiforsea --all
###########################################################
name: grabaiforsea
channels:
  - conda-forge
  - bioconda
dependencies:
  - tensorboard==1.8.0
  - tensorflow==1.8.0
  - tensorflow-gpu==1.8.0
  - xgboost==0.6a2

  - pip:
    - absl-py==0.7.1
    - alembic==0.8.10
    - apache-airflow==1.9.0
    - appdirs==1.4.3
    - asn1crypto==0.24.0
    - astor==0.8.0
    - attrs==19.1.0
    - Automat==0.7.0
    - backcall==0.1.0
    - beautifulsoup4==4.7.1
    - bleach==1.5.0
    - blinker==1.4
    - bokeh==0.13.0
    - brewer2mpl==1.4.1
    - bs4==0.0.1
    - cachetools==2.1.0
    - certifi==2018.8.24
    - cffi==1.11.5
    - chardet==3.0.4
    - click==6.7
    - cloudpickle==1.1.1
    - configparser==3.5.3
    - constantly==15.1.0
    - crcmod==1.7
    - croniter==0.3.30
    - cryptography==2.3.1
    - cycler==0.10.0
    - cytoolz==0.9.0.1
    - dask==0.17.1
    - datalab==1.1.3
    - decorator==4.4.0
    - defusedxml==0.6.0
    - dill==0.2.6
    - distributed==1.21.8
    - docutils==0.14
    - entrypoints==0.2.3
    - fastcache==1.0.2
    - fastparquet==0.3.1
    - Flask==0.11.1
    - Flask-Admin==1.4.1
    - Flask-Cache==0.13.1
    - Flask-Login==0.2.11
    - flask-swagger==0.2.13
    - Flask-WTF==0.14
    - funcsigs==1.0.0
    - future==0.16.0
    - futures==3.0.3
    - gast==0.2.2
    - ggplot==0.6.8
    - gitdb2==2.0.5
    - GitPython==2.1.11
    - google-api-core==0.1.4
    - google-api-python-client==1.6.2
    - google-auth==1.6.3
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.3.0
    - google-cloud-bigquery==1.10.0
    - google-cloud-core==0.28.1
    - google-cloud-monitoring==0.28.0
    - google-resumable-media==0.3.2
    - googleapis-common-protos==1.5.9
    - grpcio==1.21.1
    - gunicorn==19.9.0
    - h5py==2.9.0
    - heapdict==1.0.0
    - html5lib==0.9999999
    - httplib2==0.10.3
    - hyperlink==19.0.0
    - idna==2.6
    - imageio==2.4.1
    - incremental==17.5.0
    - ipykernel==4.8.2
    - ipython==6.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.2.1
    - itsdangerous==1.1.0
    - jedi==0.12.1
    - Jinja2==2.8
    - jsonschema==2.6.0
    - jupyter-client==5.2.3
    - jupyter-core==4.4.0
    - jupyter-highlight-selected-word==0.2.0
    - Keras==2.2.4
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - lime==0.1.1.23
    - llvmlite==0.29.0
    - locket==0.2.0
    - lockfile==0.12.2
    - lxml==3.8.0
    - Mako==1.0.12
    - Markdown==2.6.11
    - MarkupSafe==1.0
    - matplotlib==2.1.2
    - mistune==0.8.3
    - mltoolbox-datalab-classification-and-regression==1.0.1
    - mltoolbox-datalab-image-classification==0.2
    - mock==2.0.0
    - msgpack==0.5.6
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - networkx==2.3
    - nltk==3.2.1
    - notebook==5.6.0
    - numba==0.44.0
    - numpy==1.16.4
    - oauth2client==2.2.0
    - oauthlib==3.0.1
    - olefile==0.46
    - ordereddict==1.1
    - packaging==17.1
    - pandas==0.24.2
    - pandas-gbq==0.3.0
    - pandas-profiling==1.4.2
    - pandocfilters==1.4.2
    - parso==0.4.0
    - partd==0.3.10
    - patsy==0.5.0
    - pbr==5.1.3
    - pexpect==4.6.0
    - pickleshare==0.7.4
    - Pillow==3.4.1
    - plotly==3.10.0
    - prometheus-client==0.3.1
    - prompt-toolkit==1.0.15
    - protobuf==3.6.1
    - psutil==4.3.0
    - ptyprocess==0.6.0
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.2
    - pycparser==2.19
    - Pygments==2.1.3
    - PyJWT==1.6.4
    - pyOpenSSL==18.0.0
    - pyparsing==2.4.0
    - PySocks==1.6.8
    - python-daemon==2.1.2
    - python-dateutil==2.5.0
    - python-editor==1.0.4
    - python-nvd3==0.14.2
    - python-slugify==1.1.4
    - python-snappy==0.5.1
    - pytz==2018.4
    - PyWavelets==1.0.0
    - PyYAML==3.13
    - pyzmq==17.1.0
    - requests==2.18.4
    - requests-oauthlib==1.2.0
    - retrying==1.3.3
    - rsa==3.4.2
    - scikit-image==0.13.0
    - scikit-learn==0.19.1
    - scipy==1.0.0
    - seaborn==0.7.0
    - Send2Trash==1.5.0
    - service-identity==17.0.0
    - setproctitle==1.1.10
    - Shapely==1.6.4.post2
    - simplegeneric==0.8.1
    - simplejson==3.16.0
    - six==1.10.0
    - smmap2==2.0.5
    - sortedcontainers==2.0.5
    - soupsieve==1.9.1
    - SQLAlchemy==1.3.4
    - statsmodels==0.8.0
    - sympy==0.7.6.1
    - tabulate==0.7.7
    - tblib==1.4.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.3.1
    - tflearn==0.3.2
    - thrift==0.11.0
    - toolz==0.9.0
    - tornado==4.5.1
    - tqdm==4.32.1
    - traitlets==4.3.2
    - Twisted==18.7.0
    - Unidecode==1.0.23
    - uritemplate==3.0.0
    - urllib3==1.22
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - Werkzeug==0.15.4
    - widgetsnbextension==3.2.1
    - WTForms==2.2.1
    - zict==0.1.3
    - zope.deprecation==4.4.0
    - zope.interface==4.5.0